# SSL configuration
#
{.ListenSnipet}
#
# Note: You should disable gzip for SSL traffic.
# See: https://bugs.debian.org/773332
#
# Read up on ssl_ciphers to ensure a secure configuration.
# See: https://bugs.debian.org/765782
#
# Self signed certs generated by the ssl-cert package
# Don't use them in a production server!
#
# include snippets/snakeoil.conf;

ssl_certificate     {{ .SslPublicCertificate }};
ssl_certificate_key {{ .SslPrivateCertificate }};
ssl_protocols       {{ .SslProtocols }};
ssl_ciphers         {{ .SslCiphers }};
